In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_excel("loan_default_risk_dataset.xlsx")

In [4]:
df.head(10)

,Loan_ID,Application_Date,Age,Gender,Marital_Status,Dependents,Education_Level,Employment_Type,Years_in_Employment,Annual_Income_INR,...,Co_Applicant,Credit_Score,Credit_History_Years,Existing_Loans,Existing_Monthly_EMI_INR,Credit_Utilization_Pct,Past_Delinquencies_24M,DTI_Ratio_Pct,Loan_to_Income_Ratio,Default_Flag
0,LN100001,2022-01-01,44,Male,Married,0,Professional (CA/MBBS/Engg+),Salaried - Private,7.8,1558000,...,No,778,15.2,1,10600,39,0,47.3,0.69,0
1,LN100002,2022-01-01,31,Male,Married,4,Below 10th/High School,Self-Employed - Business,7.9,563000,...,No,646,8.2,4,10300,32,0,44.0,0.67,0
2,LN100003,2022-01-01,33,Female,Widowed,3,Postgraduate,Salaried - Private,2.4,149000,...,Yes,635,5.6,0,0,89,0,62.5,3.89,1
3,LN100004,2022-01-02,45,Female,Married,3,Higher Secondary (12th),Salaried - Private,5.1,307000,...,Yes,690,8.9,2,4700,54,1,46.4,1.07,1
4,LN100005,2022-01-02,43,Female,Married,1,Graduate,Salaried - Private,7.2,247000,...,Yes,648,13.4,2,5000,31,2,35.8,0.61,0
5,LN100006,2022-01-02,45,Male,Married,2,Higher Secondary (12th),Salaried - Private,16.2,636000,...,No,698,18.7,3,18600,69,0,79.4,2.34,0
6,LN100007,2022-01-03,41,Male,Widowed,0,Graduate,Self-Employed - Business,7.7,259000,...,Yes,679,6.6,3,7400,43,0,50.3,1.16,0
7,LN100008,2022-01-04,34,Male,Married,4,Graduate,Self-Employed - Professional,4.5,1177000,...,No,747,5.5,3,32300,28,0,78.4,0.42,0
8,LN100009,2022-01-05,34,Male,Married,0,Graduate,Salaried - Private,8.0,149000,...,No,686,5.5,3,2500,66,0,50.6,1.34,0
9,LN100010,2022-01-06,33,Female,Married,0,Graduate,Gig/Freelance,8.4,304000,...,No,590,6.7,1,1700,89,0,17.9,0.20,1

In [5]:
df.columns

Index(['Loan_ID', 'Application_Date', 'Age', 'Gender', 'Marital_Status',
       'Dependents', 'Education_Level', 'Employment_Type',
       'Years_in_Employment', 'Annual_Income_INR', 'State', 'City',
       'City_Tier', 'Residence_Type', 'Loan_Type', 'Loan_Amount_INR',
       'Tenure_Months', 'Interest_Rate_Pct', 'EMI_INR', 'Collateral_Type',
       'LTV_Pct', 'Co_Applicant', 'Credit_Score', 'Credit_History_Years',
       'Existing_Loans', 'Existing_Monthly_EMI_INR', 'Credit_Utilization_Pct',
       'Past_Delinquencies_24M', 'DTI_Ratio_Pct', 'Loan_to_Income_Ratio',
       'Default_Flag'],
      dtype='str')

In [6]:
df.shape

(2000, 31)

In [7]:
df.isnull().sum()

Loan_ID                        0
Application_Date               0
Age                            0
Gender                         0
Marital_Status                 0
Dependents                     0
Education_Level                0
Employment_Type                0
Years_in_Employment            0
Annual_Income_INR              0
State                          0
City                           0
City_Tier                      0
Residence_Type                 0
Loan_Type                      0
Loan_Amount_INR                0
Tenure_Months                  0
Interest_Rate_Pct              0
EMI_INR                        0
Collateral_Type             1022
LTV_Pct                     1022
Co_Applicant                   0
Credit_Score                   0
Credit_History_Years           0
Existing_Loans                 0
Existing_Monthly_EMI_INR       0
Credit_Utilization_Pct         0
Past_Delinquencies_24M         0
DTI_Ratio_Pct                  0
Loan_to_Income_Ratio           0
Default_Flag                   0
dtype: int64

In [8]:
df.isnull().sum().sort_values(ascending=False)

LTV_Pct                     1022
Collateral_Type             1022
Loan_ID                        0
Gender                         0
Marital_Status                 0
Application_Date               0
Age                            0
Employment_Type                0
Years_in_Employment            0
Annual_Income_INR              0
State                          0
City                           0
City_Tier                      0
Dependents                     0
Education_Level                0
Loan_Type                      0
Residence_Type                 0
Loan_Amount_INR                0
Tenure_Months                  0
EMI_INR                        0
Interest_Rate_Pct              0
Co_Applicant                   0
Credit_Score                   0
Credit_History_Years           0
Existing_Loans                 0
Existing_Monthly_EMI_INR       0
Credit_Utilization_Pct         0
Past_Delinquencies_24M         0
DTI_Ratio_Pct                  0
Loan_to_Income_Ratio           0
Default_Flag                   0
dtype: int64

In [9]:
df["Default_Flag"].value_counts()

Default_Flag
0    1747
1     253
Name: count, dtype: int64

In [10]:
df["Default_Flag"].value_counts(normalize=True) * 100

Default_Flag
0    87.35
1    12.65
Name: proportion, dtype: float64

In [11]:
df['Loan_Type'].value_counts()

Loan_Type
Personal Loan            610
Home Loan                402
Auto Loan                271
Business Loan            236
Gold Loan                209
Education Loan           176
Loan Against Property     96
Name: count, dtype: int64

In [12]:
df['Employment_Type'].value_counts()

Employment_Type
Salaried - Private              974
Self-Employed - Business        468
Salaried - Government           213
Gig/Freelance                   200
Self-Employed - Professional    136
Retired (Pension)                 9
Name: count, dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.columns = (df.columns.str.strip().str.replace(" " , "_"))

In [15]:
df.columns

Index(['Loan_ID', 'Application_Date', 'Age', 'Gender', 'Marital_Status',
       'Dependents', 'Education_Level', 'Employment_Type',
       'Years_in_Employment', 'Annual_Income_INR', 'State', 'City',
       'City_Tier', 'Residence_Type', 'Loan_Type', 'Loan_Amount_INR',
       'Tenure_Months', 'Interest_Rate_Pct', 'EMI_INR', 'Collateral_Type',
       'LTV_Pct', 'Co_Applicant', 'Credit_Score', 'Credit_History_Years',
       'Existing_Loans', 'Existing_Monthly_EMI_INR', 'Credit_Utilization_Pct',
       'Past_Delinquencies_24M', 'DTI_Ratio_Pct', 'Loan_to_Income_Ratio',
       'Default_Flag'],
      dtype='str')

In [16]:
df['Application_Date'] = pd.to_datetime(df['Application_Date'],errors = "corece")

In [17]:
df['Application_Date'].isnull().sum()

np.int64(0)

In [19]:
df.dtypes

Loan_ID                                str
Application_Date            datetime64[us]
Age                                  int64
Gender                                 str
Marital_Status                         str
Dependents                           int64
Education_Level                        str
Employment_Type                        str
Years_in_Employment                float64
Annual_Income_INR                    int64
State                                  str
City                                   str
City_Tier                              str
Residence_Type                         str
Loan_Type                              str
Loan_Amount_INR                      int64
Tenure_Months                        int64
Interest_Rate_Pct                  float64
EMI_INR                              int64
Collateral_Type                        str
LTV_Pct                            float64
Co_Applicant                           str
Credit_Score                         int64
Credit_History_Years               float64
Existing_Loans                       int64
Existing_Monthly_EMI_INR             int64
Credit_Utilization_Pct               int64
Past_Delinquencies_24M               int64
DTI_Ratio_Pct                      float64
Loan_to_Income_Ratio               float64
Default_Flag                         int64
dtype: object

In [20]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].str.strip()

C:\Users\VANSHIKA\AppData\Local\Temp\ipykernel_21752\4285325853.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

In [21]:
df['Loan_Type'].value_counts()

Loan_Type
Personal Loan            610
Home Loan                402
Auto Loan                271
Business Loan            236
Gold Loan                209
Education Loan           176
Loan Against Property     96
Name: count, dtype: int64

In [22]:
df['Employment_Type'].value_counts()

Employment_Type
Salaried - Private              974
Self-Employed - Business        468
Salaried - Government           213
Gig/Freelance                   200
Self-Employed - Professional    136
Retired (Pension)                 9
Name: count, dtype: int64

In [23]:
df["City_Tier"].value_counts()

City_Tier
Tier-2    923
Metro     548
Tier-3    353
Rural     176
Name: count, dtype: int64

In [25]:
df['Education_Level'].value_counts()

Education_Level
Graduate                        899
Postgraduate                    452
Higher Secondary (12th)         347
Professional (CA/MBBS/Engg+)    170
Below 10th/High School          132
Name: count, dtype: int64

In [26]:
df.groupby("Collateral_Type")["LTV_Pct"].apply(
    lambda x: x.isnull().sum()
)

Collateral_Type
Gold        0
Property    0
Vehicle     0
Name: LTV_Pct, dtype: int64

In [27]:
df[df["LTV_Pct"].isnull()]["Collateral_Type"].value_counts()

Series([], Name: count, dtype: int64)

In [28]:
missing = df.isnull().sum()

missing[missing > 0]

Collateral_Type    1022
LTV_Pct            1022
dtype: int64

In [29]:
df['Default_Flag'].unique()

array([0, 1])

In [30]:
df['Default_Flag'].isnull().sum()

np.int64(0)

In [32]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 24, 34, 44, 54, 64, 100],
    labels=["Under 25", "25-34", "35-44", "45-54", "55-64", "65+"]
)

In [33]:
df["Application_Year"] = df["Application_Date"].dt.year

In [34]:
df["Application_Year"].value_counts().sort_index()

Application_Year
2022    513
2023    521
2024    486
2025    480
Name: count, dtype: int64

In [35]:
df["Loan_Security"] = df["Collateral_Type"].apply(
    lambda x: "Unsecured" if pd.isna(x) else "Secured"
)

In [36]:
df.columns

Index(['Loan_ID', 'Application_Date', 'Age', 'Gender', 'Marital_Status',
       'Dependents', 'Education_Level', 'Employment_Type',
       'Years_in_Employment', 'Annual_Income_INR', 'State', 'City',
       'City_Tier', 'Residence_Type', 'Loan_Type', 'Loan_Amount_INR',
       'Tenure_Months', 'Interest_Rate_Pct', 'EMI_INR', 'Collateral_Type',
       'LTV_Pct', 'Co_Applicant', 'Credit_Score', 'Credit_History_Years',
       'Existing_Loans', 'Existing_Monthly_EMI_INR', 'Credit_Utilization_Pct',
       'Past_Delinquencies_24M', 'DTI_Ratio_Pct', 'Loan_to_Income_Ratio',
       'Default_Flag', 'Age_Group', 'Application_Year', 'Loan_Security'],
      dtype='str')

In [37]:
df.head(10)

,Loan_ID,Application_Date,Age,Gender,Marital_Status,Dependents,Education_Level,Employment_Type,Years_in_Employment,Annual_Income_INR,...,Existing_Loans,Existing_Monthly_EMI_INR,Credit_Utilization_Pct,Past_Delinquencies_24M,DTI_Ratio_Pct,Loan_to_Income_Ratio,Default_Flag,Age_Group,Application_Year,Loan_Security
0,LN100001,2022-01-01,44,Male,Married,0,Professional (CA/MBBS/Engg+),Salaried - Private,7.8,1558000,...,1,10600,39,0,47.3,0.69,0,35-44,2022,Unsecured
1,LN100002,2022-01-01,31,Male,Married,4,Below 10th/High School,Self-Employed - Business,7.9,563000,...,4,10300,32,0,44.0,0.67,0,25-34,2022,Unsecured
2,LN100003,2022-01-01,33,Female,Widowed,3,Postgraduate,Salaried - Private,2.4,149000,...,0,0,89,0,62.5,3.89,1,25-34,2022,Secured
3,LN100004,2022-01-02,45,Female,Married,3,Higher Secondary (12th),Salaried - Private,5.1,307000,...,2,4700,54,1,46.4,1.07,1,45-54,2022,Unsecured
4,LN100005,2022-01-02,43,Female,Married,1,Graduate,Salaried - Private,7.2,247000,...,2,5000,31,2,35.8,0.61,0,35-44,2022,Unsecured
5,LN100006,2022-01-02,45,Male,Married,2,Higher Secondary (12th),Salaried - Private,16.2,636000,...,3,18600,69,0,79.4,2.34,0,45-54,2022,Unsecured
6,LN100007,2022-01-03,41,Male,Widowed,0,Graduate,Self-Employed - Business,7.7,259000,...,3,7400,43,0,50.3,1.16,0,35-44,2022,Unsecured
7,LN100008,2022-01-04,34,Male,Married,4,Graduate,Self-Employed - Professional,4.5,1177000,...,3,32300,28,0,78.4,0.42,0,25-34,2022,Unsecured
8,LN100009,2022-01-05,34,Male,Married,0,Graduate,Salaried - Private,8.0,149000,...,3,2500,66,0,50.6,1.34,0,25-34,2022,Secured
9,LN100010,2022-01-06,33,Female,Married,0,Graduate,Gig/Freelance,8.4,304000,...,1,1700,89,0,17.9,0.20,1,25-34,2022,Secured

In [38]:
df["Credit_Score_Band"] = pd.cut(
    df["Credit_Score"],
    bins=[0, 579, 669, 739, 799, 900],
    labels=["Poor", "Fair", "Good", "Very Good", "Excellent"],
    include_lowest=True
)

In [39]:
df["DTI_Band"] = pd.cut(
    df["DTI_Ratio_Pct"],
    bins=[0, 20, 35, 50, 65, 100],
    labels=["Low", "Moderate", "High", "Very High", "Extreme"],
    include_lowest=True
)

In [40]:
df["LTV_Band"] = pd.cut(
    df["LTV_Pct"],
    bins=[0, 60, 80, 90, 100],
    labels=["Low", "Moderate", "High", "Very High"],
    include_lowest=True
)

In [41]:
df[[
    "Credit_Score",
    "Credit_Score_Band",
    "DTI_Ratio_Pct",
    "DTI_Band",
    "LTV_Pct",
    "LTV_Band"
]].head(20)

,Credit_Score,Credit_Score_Band,DTI_Ratio_Pct,DTI_Band,LTV_Pct,LTV_Band
0,778,Very Good,47.3,High,NaN,NaN
1,646,Fair,44.0,High,NaN,NaN
2,635,Fair,62.5,Very High,90.0,High
3,690,Good,46.4,High,NaN,NaN
4,648,Fair,35.8,High,NaN,NaN
5,698,Good,79.4,Extreme,NaN,NaN
6,679,Good,50.3,Very High,NaN,NaN
7,747,Very Good,78.4,Extreme,NaN,NaN
8,686,Good,50.6,Very High,72.0,Moderate
9,590,Fair,17.9,Low,67.5,Moderate
10,775,Very Good,22.4,Moderate,71.7,Moderate
11,764,Very Good,39.2,High,40.7,Low
12,632,Fair,55.7,Very High,87.3,High
13,780,Very Good,81.4,Extreme,75.0,Moderate
14,778,Very Good,73.7,Extreme,81.3,High
15,624,Fair,29.2,Moderate,NaN,NaN
16,562,Poor,67.7,Extreme,56.2,Low
17,725,Good,33.3,Moderate,NaN,NaN
18,682,Good,75.4,Extreme,69.9,Moderate
19,598,Fair,14.6,Low,NaN,NaN

In [42]:
df["LTV_Band"].isna().sum()

np.int64(1022)

In [43]:
df.to_excel("loan_default_risk_cleaned.xlsx", index=False)